//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryProject.EFDF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenderlinkedTopic
    {
        public int ID { get; set; }
        public string Topic { get; set; }
        public Nullable<int> GID { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
