//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryProject.EFDF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInterest
    {
        public int ID { get; set; }
        public string InterestedTopic { get; set; }
        public Nullable<int> ProfileDetId { get; set; }
    
        public virtual ItemData ItemData { get; set; }
    }
}
