//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryProject.EFDF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemData()
        {
            this.ItemInterests = new HashSet<ItemInterest>();
        }
    
        public int ProfileDetId { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string ItemType { get; set; }
        public Nullable<decimal> AvailableCount { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> ItemIntroDate { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Continent { get; set; }
        public string Country { get; set; }
        public string ConfirmText1 { get; set; }
        public string ConfirmText2 { get; set; }
        public string InterestedTopicMulti { get; set; }
        public byte[] FileDoc { get; set; }
        public byte[] ItemImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemInterest> ItemInterests { get; set; }
    }
}
