//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryProject.EFDF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBFORMSEntities : DbContext
    {
        public WEBFORMSEntities()
            : base("name=WEBFORMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<ItemData> ItemDatas { get; set; }
        public virtual DbSet<ItemInterest> ItemInterests { get; set; }
        public virtual DbSet<GenderlinkedTopic> GenderlinkedTopics { get; set; }
        public virtual DbSet<GRIDSIMPLEEDIT> GRIDSIMPLEEDITs { get; set; }
    }
}
